"""initial schema

Revision ID: 39e284ed2d7f
Revises:
Create Date: 2026-07-18 16:48:17.934191
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "39e284ed2d7f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("invite_code", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("departure_location", sa.String(length=160), nullable=False),
        sa.Column("departure_latitude", sa.Float(), nullable=False),
        sa.Column("departure_longitude", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("join_closed", sa.Boolean(), nullable=False),
        sa.Column("redraw_allowed", sa.Boolean(), nullable=False),
        sa.Column("redraw_count", sa.Integer(), nullable=False),
        sa.Column("selected_place_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rooms_invite_code"), "rooms", ["invite_code"], unique=True)
    op.create_index(op.f("ix_rooms_mode"), "rooms", ["mode"], unique=False)
    op.create_index(op.f("ix_rooms_status"), "rooms", ["status"], unique=False)
    op.create_index("ix_rooms_status_mode", "rooms", ["status", "mode"], unique=False)
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("anonymous_session_id", sa.String(length=64), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=True),
        sa.Column("event_name", sa.String(length=40), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_events_anonymous_session_id"),
        "analytics_events",
        ["anonymous_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_event_name"), "analytics_events", ["event_name"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_events_room_id"), "analytics_events", ["room_id"], unique=False
    )
    op.create_table(
        "omys_conditions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("transport_mode", sa.String(length=20), nullable=False),
        sa.Column("max_travel_minutes", sa.Integer(), nullable=False),
        sa.Column("budget_per_person", sa.Integer(), nullable=True),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("preferred_categories", sa.JSON(), nullable=False),
        sa.Column("indoor_outdoor", sa.String(length=20), nullable=True),
        sa.Column("excluded_activities", sa.JSON(), nullable=False),
        sa.Column("includes_food", sa.Boolean(), nullable=True),
        sa.Column("accessibility", sa.String(length=120), nullable=True),
        sa.Column("total_available_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id"),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("nickname", sa.String(length=20), nullable=False),
        sa.Column("participant_token", sa.String(length=64), nullable=False),
        sa.Column("is_host", sa.Boolean(), nullable=False),
        sa.Column("submission_completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "participant_token", name="uq_participant_room_token"),
    )
    op.create_index(
        op.f("ix_participants_participant_token"),
        "participants",
        ["participant_token"],
        unique=True,
    )
    op.create_index(op.f("ix_participants_room_id"), "participants", ["room_id"], unique=False)
    op.create_table(
        "place_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("participant_id", sa.String(length=36), nullable=True),
        sa.Column("external_place_id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("address", sa.String(length=240), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("price_level", sa.Integer(), nullable=True),
        sa.Column("business_status", sa.String(length=40), nullable=True),
        sa.Column("open_now", sa.Boolean(), nullable=True),
        sa.Column("next_close_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_public_outdoor", sa.Boolean(), nullable=False),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("place_url", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(["participant_id"], ["participants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "room_id", "participant_id", "external_place_id", name="uq_candidate_submission"
        ),
    )
    op.create_index(
        op.f("ix_place_candidates_room_id"), "place_candidates", ["room_id"], unique=False
    )
    with op.batch_alter_table("rooms") as batch_op:
        batch_op.create_foreign_key(
            "fk_room_selected_place", "place_candidates", ["selected_place_id"], ["id"]
        )
    op.create_table(
        "selections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("place_candidate_id", sa.String(length=36), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_candidate_id"],
            ["place_candidates.id"],
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "attempt", name="uq_selection_room_attempt"),
        sa.UniqueConstraint("room_id", "place_candidate_id", name="uq_selection_room_place"),
    )
    op.create_index(op.f("ix_selections_room_id"), "selections", ["room_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_selections_room_id"), table_name="selections")
    op.drop_table("selections")
    with op.batch_alter_table("rooms") as batch_op:
        batch_op.drop_constraint("fk_room_selected_place", type_="foreignkey")
    op.drop_index(op.f("ix_place_candidates_room_id"), table_name="place_candidates")
    op.drop_table("place_candidates")
    op.drop_index(op.f("ix_participants_room_id"), table_name="participants")
    op.drop_index(op.f("ix_participants_participant_token"), table_name="participants")
    op.drop_table("participants")
    op.drop_table("omys_conditions")
    op.drop_index(op.f("ix_analytics_events_room_id"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_event_name"), table_name="analytics_events")
    op.drop_index(op.f("ix_analytics_events_anonymous_session_id"), table_name="analytics_events")
    op.drop_table("analytics_events")
    op.drop_index("ix_rooms_status_mode", table_name="rooms")
    op.drop_index(op.f("ix_rooms_status"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_mode"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_invite_code"), table_name="rooms")
    op.drop_table("rooms")
    # ### end Alembic commands ###
